version: '3.5'

services:

  db:
    container_name: db
    hostname: db
    image: postgres:latest
    command: postgres -N 500
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oltpbench
    ports:
      - "5432:5432"

  db-ui:
    container_name: db-ui
    hostname: db-ui
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8080
    links:
      - db
    ports:
      - "8888:8080"
    volumes:
      - ${PWD}/servers.json:/pgadmin4/servers.json