type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: false
loaderthreads: 1
terminals: 1
yaml_version: v1.1
works:
    work:
        rate: unlimited
        serial: true

microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal1
    properties:
        setAutoCommit: true
        # Goal 1 - 4 :: create table with PK -> create 10 index -> load data (10 index)
        workload: create10index_load
        tableName: orders
        columns: 15
        rows: 3000000
        indexes: 10
        filePath: orders.csv
        stringLength: 32
        recreateCsvIfExists: false
