#TEST FOR YUGABYTE Colocated TABLES
#GOAL1 Impact of index type on Orderby
#TESTS:
#Orderby clause on non indexed column of bigint datatype
#Orderby clause on pkey of bigint datatype
#Orderby clause on secondary indexed column of bigint datatype
type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{user}}
password: {{pwd}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
works:
    work:
        time_secs: 300
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS nonIndexed1M_1;
            - DROP TABLE IF EXISTS pkeyBigint1M_1;
            - DROP TABLE IF EXISTS Indexed1M_1;
            - CREATE TABLE nonIndexed1M_1(col_bigint_id_1 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500));
            - CREATE TABLE pkeyBigint1M_1(col_bigint_id_1 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1));
            - CREATE TABLE Indexed1M_1(col_bigint_id_1 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500));
            - CREATE INDEX ON Indexed1M_1(col_bigint_id_1);
            - CREATE INDEX ON Indexed1M_1(col_varchar10_id_1);
            - CREATE INDEX ON Indexed1M_1(col_varchar500_id_1);
            - CREATE INDEX ON Indexed1M_1(col_float5_1);

        loadRules:
              - table: nonIndexed1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 1
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 5
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]
              - table: pkeyBigint1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 1
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 5
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]
              - table: Indexed1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 1
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 5
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]
        executeRules:
            - workload: ORDG1_ybc_ordby_bigint_non_indexed_column
              run:
                  - name: yb_ordby_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from nonIndexed1M_1 order by col_bigint_id_1
            - workload: ORDG1_ybc_ordby_bigint_pkey_column
              run:
                  - name: yb_ordby_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from pkeyBigint1M_1 order by col_bigint_id_1
            - workload: ORDG1_ybc_ordby_bigint_secondary_indexed_column
              run:
                  - name: yb_ordby_bigint_non_indexed_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from Indexed1M_1 order by col_bigint_id_1