type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: false
loaderthreads: 1
terminals: 1
works:
    work:
        rate: unlimited
        serial: true
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal3
    properties:
        # Goal3 - 3 :: create table with 15 fields -> load data for 300M rows (only PK)
        workload: load_300Mrows
        tableName: orders
        columns: 15
        rows: 300000000
        filePath: orders.csv
        stringLength: 32
