#TEST FOR YUGABYTE REGULAR TABLES
#GOAL3 Impact of datatype on Orderby clause
#TESTS:
#Impact of orderby clause on PKEY of bigint datatype
#Impact of orderby clause on PKEY of varchar datatype
#Impact of orderby clause on PKEY of uuid datatype
type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require
username: {{user}}
password: {{pwd}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
works:
    work:
        time_secs: 300
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
          - DROP TABLE IF EXISTS pkeyBigint1M_1;
          - DROP TABLE IF EXISTS pkeyVarchar1001M_1;
          - DROP TABLE IF EXISTS pkeyUuid1M_1;
          - CREATE TABLE pkeyBigint1M_1(col_bigint_id_1 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1 ASC));
          - CREATE TABLE pkeyVarchar1001M_1(col_varchar100_pid_1 varchar(100), col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_varchar100_pid_1 ASC));
          - CREATE TABLE pkeyUuid1M_1(col_uuid_id_1 uuid, col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_uuid_id_1 ASC));

        loadRules:
              - table: pkeyBigint1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 1
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 5
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]
              - table: pkeyVarchar1001M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_varchar100_pid_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_bigint_
                      count: 5
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]
              - table: pkeyUuid1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_uuid_id_
                      count: 1
                      util: RandomUUID
                    - name: col_bigint_
                      count: 5
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]

        executeRules:
            - workload: ORDG3_yb_ordby_bigint_pkey_column
              run:
                  - name: yb_ordby_bigint_pkey_column
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from pkeyBigint1M_1 order by col_bigint_id_1
            - workload: ORDG3_yb_ordby_varchar_pkey_column
              run:
                  - name: yb_ordby_varchar_pkey_column
                    weight: 100
                    queries:
                        - query: select col_varchar100_pid_1 from pkeyVarchar1001M_1 order by col_varchar100_pid_1
            - workload: ORDG3_yb_ordby_uuid_pkey_column
              run:
                  - name: yb_ordby_uuid_pkey_column
                    weight: 100
                    queries:
                        - query: select col_uuid_id_1 from pkeyUuid1M_1 order by col_uuid_id_1