type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
works:
    work:
        time_secs: 600
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS Hashtbl_1;
            - DROP TABLE IF EXISTS Hashtbl_2;
            - CREATE TABLE Hashtbl_1(col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_bigint_id_4 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1));
            - CREATE INDEX ON Hashtbl_1(col_bigint_id_2);
            - CREATE INDEX ON Hashtbl_1(col_bigint_id_3);
            - CREATE TABLE Hashtbl_2(col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_bigint_id_4 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1));
            - CREATE INDEX ON Hashtbl_2(col_bigint_id_2);
            - CREATE INDEX ON Hashtbl_2(col_bigint_id_3);
        cleanup:
            - DROP TABLE IF EXISTS Hashtbl_1;
            - DROP TABLE IF EXISTS Hashtbl2;

        loadRules:
              - table: Hashtbl_
                count: 2
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 4
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 2
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]

        executeRules:
            - workload: JOING1_1_join_on_pk_of_hash_tbl
              run:
                  - name: join_on_pk_of_hash_tbl
                    weight: 100
                    queries:
                        - query: select Hashtbl_1.col_bigint_id_1,Hashtbl_2.col_bigint_id_1 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_1=Hashtbl_2.col_bigint_id_1

            - workload: JOING1_2_join_on_pk_of_hash_tbl_with_1_filter
              run:
                  - name: join_on_pk_of_hash_tbl
                    weight: 100
                    queries:
                        - query: select Hashtbl_1.col_bigint_id_1,Hashtbl_2.col_bigint_id_1 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_1=Hashtbl_2.col_bigint_id_1 where Hashtbl_1.col_bigint_id_1<100001

            - workload: JOING1_3_join_on_pk_of_hash_tbl_with_2_filter
              run:
                  - name: join_on_pk_of_hash_tbl
                    weight: 100
                    queries:
                        - query: select Hashtbl_1.col_bigint_id_1,Hashtbl_2.col_bigint_id_1 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_1=Hashtbl_2.col_bigint_id_1 where Hashtbl_1.col_bigint_id_1<100001 and Hashtbl_2.col_bigint_id_1<100001

            - workload: JOING1_4_join_on_hashidx_of_hash_tbl
              run:
                  - name: join_on_pk_of_hash_tbl
                    weight: 100
                    queries:
                        - query: select Hashtbl_1.col_bigint_id_2,Hashtbl_2.col_bigint_id_2 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_2=Hashtbl_2.col_bigint_id_2

            - workload: JOING1_5_join_on_hashidx_of_hash_tbl_with_1_filter
              run:
                  - name: join_on_pk_of_hash_tbl
                    weight: 100
                    queries:
                        - query: select Hashtbl_1.col_bigint_id_2,Hashtbl_2.col_bigint_id_2 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_2=Hashtbl_2.col_bigint_id_2 where Hashtbl_1.col_bigint_id_2<100001

            -   workload: JOING1_6_join_on_rangeidx_of_hash_tbl
                run:
                    -   name: join_on_pk_of_hash_tbl
                        weight: 100
                        queries:
                            -   query: select Hashtbl_1.col_bigint_id_3,Hashtbl_2.col_bigint_id_3 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_3=Hashtbl_2.col_bigint_id_3

            -   workload: JOING1_7_join_on_rangeidx_of_hash_tbl_with_1_filter
                run:
                    -   name: join_on_pk_of_hash_tbl
                        weight: 100
                        queries:
                            -   query: select Hashtbl_1.col_bigint_id_3,Hashtbl_2.col_bigint_id_3 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_3=Hashtbl_2.col_bigint_id_3 where Hashtbl_1.col_bigint_id_3<100001

            -   workload: JOING1_8_join_on_nonidx_of_hash_tbl
                run:
                    -   name: join_on_pk_of_hash_tbl
                        weight: 100
                        queries:
                            -   query: select Hashtbl_1.col_bigint_id_4,Hashtbl_2.col_bigint_id_4 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_4=Hashtbl_2.col_bigint_id_4

            -   workload: JOING1_9_join_on_nonidx_of_hash_tbl_with_1_filter
                run:
                    -   name: join_on_pk_of_hash_tbl
                        weight: 100
                        queries:
                            -   query: select Hashtbl_1.col_bigint_id_4,Hashtbl_2.col_bigint_id_4 from Hashtbl_1 join Hashtbl_2 on Hashtbl_1.col_bigint_id_4=Hashtbl_2.col_bigint_id_4 where Hashtbl_1.col_bigint_id_4<100001