type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: false
loaderthreads: 1
terminals: 1

works:
    work:
        rate: unlimited
        serial: true
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal4
    properties:
        # Goal4 - 1 :: create table with 10 fields, 3M rows -> load data (only PK)
        workload: create_10fields_table_then_load
        tableName: orders
        columns: 10
        rows: 3000000
        filePath: orders.csv
        stringLength: 32
