type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS CompositeRangetbl_1;
            - CREATE TABLE CompositeRangetbl_1(col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_bigint_id_4 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1 ASC, col_bigint_id_2 ASC));

        cleanup:
            - DROP TABLE IF EXISTS CompositeRangetbl_1;

        loadRules:

              - table: CompositeRangetbl_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 4
                      util: PrimaryIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 2
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]

        executeRules:

            - workload: INDG4_1_rangetbl_range_lookup_index_scan_using_comp_pkey_first_part_range
              customTags: schematype=regular,partition=range,pkey=composite,cardinality=single,projection=all,filtercount=one,filteron=rangepkey,filtertype=comparision,queryshape=scan
              run:
                  - name: hashtbl_index_scan_using_sec_index
                    weight: 100
                    queries:
                        - query: select * from CompositeRangetbl_1 where col_bigint_id_1>500000

            - workload: INDG4_2_rangetbl_range_lookup_index_scan_using_comp_pkey_sec_part_range
              customTags: schematype=regular,partition=range,pkey=composite,cardinality=single,projection=all,filtercount=one,filteron=rangepkey,filtertype=comparision,queryshape=scan
              run:
                  - name: hashtbl_index_scan_using_sec_index
                    weight: 100
                    queries:
                        - query: select * from CompositeRangetbl_1 where col_bigint_id_2>500000

            - workload: INDG4_3_rangetbl_range_lookup_index_scan_using_comp_pkey_using_two_conditions_range
              customTags: schematype=regular,partition=range,pkey=composite,cardinality=single,projection=all,filtercount=two,filteron=rangepkey,filtertype=comparision,queryshape=scan
              run:
                  - name: hashtbl_index_scan_using_sec_index
                    weight: 100
                    queries:
                        - query: select * from CompositeRangetbl_1 where col_bigint_id_1>250000 and col_bigint_id_2<750000

            - workload: INDG4_4_rangetbl_range_lookup_index_scan_using_pkey_two_conditions_range
              customTags: schematype=regular,partition=range,pkey=composite,cardinality=single,projection=all,filtercount=two,filteron=rangepkey,filtertype=comparision,queryshape=scan
              run:
                  - name: hashtbl_index_scan_pkey
                    weight: 100
                    queries:
                        - query: select * from CompositeRangetbl_1 where col_bigint_id_1>250000 and col_bigint_id_1<750000
